### ISSUE TITLE
Fatal error: Uncaught ClassNotFoundException: Class raklib\protocol\DATA_PACKET_D

### ISSUE THREAD

**Issue by thedeibo** [PocketMine/PocketMine-MP#4002]
I TESTED the new commit out, and got this. 

```
[12:26:20] [Server thread/WARNING]: Non-packaged PocketMine-MP installation detected, do not use on production.
[12:26:20] [Server thread/INFO]: Loading pocketmine.yml...
[12:26:20] [Server thread/INFO]: Loading server properties...
[12:26:20] [Server thread/INFO]: language.selected
[12:26:20] [Server thread/INFO]: pocketmine.server.start
[12:26:20] [Server thread/INFO]: pocketmine.server.networkStart
[12:26:20] [Server thread/INFO]: pocketmine.server.info
[12:26:20] [Server thread/INFO]: pocketmine.server.license
[12:26:20] [Server thread/INFO]: Loading recipes...
[12:26:20] [Server thread/INFO]: pocketmine.plugin.load

Fatal error: Uncaught ClassNotFoundException: Class raklib\protocol\DATA_PACKET_D not found in C:\Users\TheDeibo\Documents\_PM\src\spl\BaseClassLoader.php:144
Stack trace:
#0 [internal function]: BaseClassLoader->loadClass('raklib\\protocol...')
#1 C:\Users\TheDeibo\Documents\_PM\src\raklib\server\SessionManager.php(425): spl_autoload_call('raklib\\protocol...')
#2 C:\Users\TheDeibo\Documents\_PM\src\raklib\server\SessionManager.php(80): raklib\server\SessionManager->registerPackets()
#3 C:\Users\TheDeibo\Documents\_PM\src\raklib\server\RakLibServer.php(236): raklib\server\SessionManager->__construct(Object(raklib\server\RakLibServer), Object(raklib\server\UDPServerSocket))
#4 [internal function]: raklib\server\RakLibServer->run()
#5 {main}
  thrown in C:\Users\TheDeibo\Documents\_PM\src\spl\BaseClassLoader.php on line 144
[12:26:21] [Server thread/INFO]: pocketmine.plugin.enable
[12:26:21] [Server thread/INFO]: [DevTools] Registered folder plugin loader
[12:26:21] [Server thread/NOTICE]: pocketmine.level.notFound
[12:26:21] [Server thread/INFO]: pocketmine.level.preparing
[12:26:21] [Server thread/NOTICE]: pocketmine.level.backgroundGeneration
[12:26:21] [Server thread/INFO]: pocketmine.server.query.start
[12:26:21] [Server thread/INFO]: pocketmine.server.query.info
[12:26:21] [Server thread/INFO]: pocketmine.server.query.running
[12:26:21] [Server thread/INFO]: pocketmine.server.defaultGameMode
[12:26:21] [Server thread/INFO]: pocketmine.server.startFinished
[12:26:21] [Server thread/CRITICAL]: pocketmine.server.networkError

**Comment by PEMapModder** [comment]
You have a corrupted clone.
