### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by Atief123** [PocketMine/PocketMine-MP#4124]
I cant start my server. 

```
[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [15:28:48] warning> Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] [15:28:48] system> -------------------------------------------------------------------------------------------
[Server] [15:28:48] system> | _ _ _ __ __ _ |
[Server] [15:28:48] system> | (_) (_) | | \/ (_) |
[Server] [15:28:48] system> | _ _ __ ___ __ _ __ _ _ ___ __ _| | \ / |_ _ __ ___ |
[Server] [15:28:48] system> | | | '_ ` _ \ / _` |/ _` | |/ __/ _` | | |\/| | | '_ \ / _ \ ImagicalMine 1.0dev |
[Server] [15:28:48] system> | | | | | | | | (_| | (_| | | (_| (_| | | | | | | | | | __/ |
[Server] [15:28:48] system> | |_|_| |_| |_|\__,_|\__, |_|\___\__,_|_|_| |_|_|_| |_|\___| for MCPE v0.14.0.1 alpha |
[Server] [15:28:48] system> | __/ | |
[Server] [15:28:48] system> | |___/ |
[Server] [15:28:48] system> ------------------------------------------------------------------------------------------- 
[Server] [15:28:48] system> 
[Server] [15:28:48] system> ImagicalMine is a third-party build of PocketMine-MP, distributed under the LGPL licence
[Server] [15:28:48] system> Loading ImagicalMine system files....
[Server] 
[Server] Fatal error: Uncaught exception 'RuntimeException' with message 'yaml_parse(): end of stream reached without finding document 0' in phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/utils/Config.php:148
[Server] Stack trace:
[Server] #0 [internal function]: ExceptionHandler::handler(2, 'yaml_parse(): e...', 'phar:///storage...', 148, Array)
[Server] #1 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/utils/Config.php(148): yaml_parse('')
[Server] #2 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/utils/Config.php(85): pocketmine\utils\Config->load('/storage/emulat...', 2, Array)
[Server] #3 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/Server.php(1587): pocketmine\utils\Config->__construct('/storage/emulat...', 2, Array)
[Server] #4 phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/PocketMine.php(469): pocketmine\Server->__construct(Object(pocketmine\CompatibleClassLoader), Object(pocketmine\utils\MainLogger), 'phar:///storage...', '/storage/emulat...', '/stor in phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 148



PLZZZZZZ HELP

**Comment by jojoe77777** [comment]
You are not using PocketMine.

**Comment by GlitchPlayer** [comment]
Post this issue on imagicalmine repository.
